### PR TITLE
add environment variables to docker entrypoint

### PR DESCRIPTION
**Pull request by dekonnection**
Hi, and thanks a lot for this program !
It works perfectly with my OfficeJet 3830.

SInce I'm using it with K8s, I found that some useful parameters were missing in the docker entrypoint (like for setting the resolution, etc.), this PR just adds that :)

Have a great day

### CODE REVIEW

**Review by manuc66 — COMMENTED** [review]
Sounds great, may I ask you to improve the readme as well?

**Comment by dekonnection** [comment]
Oh yes, I forgot that, will do :)

**Comment by dekonnection** [comment]
I added the following things to the README:
- the exhaustive list of envvars
- the model of my printer
- an example manifest for K8s

I reordered a thing or two, of course modify it or let me know if it's not to your taste 👍

**Comment by manuc66** [comment]
Thanks you @dekonnection !

**Pull request merged**
